Add support for span logs
wavefrontHQ/wavefront-sdk-csharp pull request #26
Opened 2019-04-13 00:23 UTC by hanwavefront

2019-04-13 00:57 UTC, sushantdewan123 requested changes

2019-04-13 00:57 UTC, sushantdewan123 commented on Wavefront.SDK.CSharp/Common/Utils.cs
> +                    continue;
Emit a warning message  that the span log is not in the range?

2019-04-13 00:57 UTC, sushantdewan123 commented on Wavefront.SDK.CSharp/Common/Utils.cs
> +                sb.Append("{");
why not use some JSON library to construct the object?

2019-04-15 22:08 UTC, vikramraman approved these changes

2019-04-15 22:08 UTC, merged